
---
title: "BMI Calculator Documentation"
author: "Simon Geletta"
date: "Friday, March 20, 2015"
output: html_document
---

###How the BMI Calculator App Works
The BMI Calculator is a simple calculator that takes in the height and weight of an individual and calculates the Body Mass score for a given individual. In order to correctly calculate BMI the calculator expects the measurements to be in  "imperial" units. If measurements are entered in any other units the calculation will not give correct results.

Two slider controls are used to input the height measurements - one for the "feet", and the other one for "inches". 
To input weight measurement, simply use pounds. The equation used for the calculation is as follow:
$$\frac{wt} {ht^2} * 703.07$$

Where: 

* wt = Weight in pounds

* ht = height in inches

In addition to giving the actual BMI score, the application also gives a "cue" as to the status of health of the individual with the BMI.

* If the BMI level is between 18 and 25 this is a normal BMI score. To show this normalcy, the score is shown on a green background space.

* If the BMI is between greater than 25 but less than or equal to 28 then the application shows that this is an "overweight BMI" by showing the score in a yellow background

* If the BMI is greater than or equal to 29 then this is an "obese" BMI, and to show this the application background shows in red.

####Hope the application will help you keep fit!!

To use the BMI Calculator App follow this link: [Launch the app](http://sgeletta.shinyapps.io/BMI_Calc).

